/*
 * tokenizer-parity.test.js - byte-exact parity between training/s1tokenize.py
 * and web/executor/js/s1tokenize.js.
 *
 * Vectors were generated by gen_vectors.py (same directory) from the Python
 * reference implementation: vectors.json (68 handcrafted) and
 * fuzz_vectors.json (200 seeded random steps). Regenerate with:
 *   python3 gen_vectors.py
 *
 * Run: node tokenizer-parity.test.js   (from tests/tokenizer-executor/)
 *
 * Each ok vector: JS encodeStep output must be byte-identical to the Python
 * output (compared as canonical JSON strings). Each error vector: JS must
 * throw the same error name and message as Python.
 *
 * Deliberately NOT covered (documented divergences between the two ports):
 *  - bool token ids: Python treats True as int 1; JS rejects non-numbers.
 *  - non-string field entries: Python raises TypeError; JS raises ValueError.
 *  - lone surrogates: Python utf-8 encode raises UnicodeEncodeError; the JS
 *    TextEncoder substitutes U+FFFD.
 *  - single quotes inside field text on error paths: Python repr() switches
 *    to double quotes; the JS pyRepr always single-quotes.
 */
"use strict";

global.self = global; /* BEFORE requiring UMD modules */

var assert = require("assert");
var fs = require("fs");
var path = require("path");

var ST = require(path.join(__dirname, "..", "..", "web", "executor", "js",
  "s1tokenize.js"));

var passed = 0, failed = 0;
function check(cond, msg) {
  passed++;
  try {
    assert.ok(cond, msg);
  } catch (e) {
    failed++;
    console.error("FAIL:", msg, "-", e.message);
  }
}

function load(name) {
  return JSON.parse(fs.readFileSync(path.join(__dirname, name), "utf8")).vectors;
}

/* Canonical comparison form: fixed key order, plain JSON. */
function norm(r) {
  return JSON.stringify({
    tok_ids: r.tok_ids,
    field_hash: r.field_hash,
    name_hash: r.name_hash,
    menu_mask: r.menu_mask
  });
}

function runSuite(vectors, label) {
  var n = 0;
  vectors.forEach(function (v) {
    n++;
    if (v.ok) {
      var got;
      try {
        got = ST.encodeStep(v.ids, v.fields);
      } catch (e) {
        check(false, label + " " + v.id + ": JS threw unexpectedly: " +
          e.name + ": " + e.message);
        return;
      }
      check(norm(got) === JSON.stringify(v.expected),
        label + " " + v.id + ": byte-identical output");
    } else {
      var threw = null;
      try {
        ST.encodeStep(v.ids, v.fields);
      } catch (e) {
        threw = e;
      }
      check(threw !== null, label + " " + v.id + ": JS threw like Python");
      if (threw) {
        check(threw.name === v.error.name,
          label + " " + v.id + ": error name " + threw.name +
          " === Python " + v.error.name);
        check(threw.message === v.error.message,
          label + " " + v.id + ": error message matches Python");
      } else {
        passed += 2; /* keep the count honest: name+message checks skipped */
        failed += 2;
        console.error("FAIL:", label, v.id, "- no throw; Python said:",
          JSON.stringify(v.error));
      }
    }
  });
  return n;
}

var handcrafted = load("vectors.json");
var fuzz = load("fuzz_vectors.json");

var nHand = runSuite(handcrafted, "vector");
var nFuzz = runSuite(fuzz, "fuzz");

/* ---- embedded SHA-256 sanity (NIST test vectors) ---- */
check(ST.sha256Hex("abc") ===
  "ba7816bf8f01cfea414140de5dae2223b00361a396177a9cb410ff61f20015ad",
  "sha256('abc') matches the NIST test vector");
check(ST.sha256Hex("") ===
  "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855",
  "sha256('') matches the NIST test vector");
check(ST.sha256Hex("The quick brown fox jumps over the lazy dog") ===
  "d7a8fbb307d7809469ca9abcb0082e4f8d5651e46d3cdb762d02d0bf37c9e592",
  "sha256(fox) matches the NIST test vector");

/* ---- exported constants (frozen, specs/token-schema.json 1.0.0) ---- */
check(ST.BOS === 0 && ST.EOS === 1, "BOS/EOS constants");
check(ST.SNAPSHOT_SEP === 2 && ST.ANNOT_SEP === 3 && ST.MENU_SEP === 4,
  "separator constants");
check(ST.NODE_LO === 32 && ST.NODE_HI === 96, "node range");
check(ST.EDGE_LO === 96 && ST.EDGE_HI === 160, "edge range");
check(ST.ANNOT_LO === 160 && ST.ANNOT_HI === 224, "annotation range");
check(ST.MENU_LO === 224 && ST.MENU_HI === 288, "menu range");

/* ---- canonicalFields direct checks ---- */
check(ST.canonicalFields(JSON.parse('{"b":1,"a":2}')) === '{"a":2,"b":1}',
  "canonicalFields sorts keys");
check(ST.canonicalFields(JSON.parse('{"x":40}')) === '{"x":40}',
  "canonicalFields keeps int 40 as 40");
check(ST.canonicalFields({ s: "Montréal 🎉" }) ===
  '{"s":"Montr\\u00e9al \\ud83c\\udf89"}',
  "canonicalFields escapes non-ASCII like Python ensure_ascii");

/* ---- stableHash range contract ---- */
for (var b = 0; b < 50; b++) {
  var h = ST.stableHash("probe-" + b, 4096);
  if (!(h >= 0 && h < 4096)) {
    check(false, "stableHash in [0,4096)");
    break;
  }
}
check(true, "stableHash stays inside [0, buckets) over 50 probes");

console.log("vectors: " + nHand + " handcrafted, " + nFuzz + " fuzz");
if (failed > 0) {
  console.error("FAILED: " + failed + " of " + passed);
  process.exitCode = 1;
} else {
  console.log("PASS " + passed);
}
